Update verify-exercises script to exist with non-zero code when tests fail. (#56)
* Skip tests in high-scores and resistor-color.
Update the testing scripts to error if there are multiple unskipped tests.

* change of direction: no skipped tests

* removed skips from difference-of-squares, grains, leap and two-fer

* remove the bit in run-test that unskips: it's now useless

* ...except now we need to copy the test file to the temp dir.
Also, ensure a failure exit status when tests fail

diff --git a/bin/verify-exercises b/bin/verify-exercises
--- a/bin/verify-exercises
+++ b/bin/verify-exercises
@@ -17,10 +17,22 @@
 
 cd "$(realpath "$(dirname "$0")/..")"
 shopt -s nullglob
+failures=()
 
 for exercise_dir in exercises/{concept,practice}/*/; do
     if [[ -d $exercise_dir ]]; then
         echo "Checking $(basename "${exercise_dir}") exercise..."
-        bin/run-test.sh "${exercise_dir}"
+        bin/run-test.sh "${exercise_dir}" || failures+=( "$(basename "${exercise_dir}")" )
     fi
 done
+
+if (( ${#failures[@]} > 0 )); then
+    {
+        echo '==========================='
+        echo '[ERROR] exercises failures!'
+        for f in "${failures[@]}"; do printf -- '- %s\n' "$f"; done
+    } >&2
+    exit 1
+fi
+
+exit 0
